<<<<<<< HEAD
=======
os:
  - osx
  - linux

>>>>>>> 879a237667760f09187e79977655170214e8d89a
language: cpp

sudo: required

compiler:
  - clang
  - g++

before_install:
 - sh .travis-deps.sh

script:
 - sh .travis-build.sh
