# it seems that Qt is only installed by default on unstable os at the moment
os: unstable

# shallow clone
clone_depth: 5

environment:
  QTDIR: C:\Qt\5.4\msvc2013_64_opengl

platform:
  - x64

configuration:
  - Debug

install:
  - git submodule update --init --recursive --depth 20

before_build:
  - cd QT
  - qmake -r -tp vc HiveQt.pro